-- SELEÇÃO SIMPLES DE MULTIPLAS COLUNAS
SELECT NM_EMPREGADO, FUNCAO, SALARIO
	FROM EMPREGADO;

-- SELEÇÃO USANDO APELIDOS NAS TABELAS (AS)
SELECT NM_EMPREGADO AS NOME, FUNCAO AS FUNÇÃO, SALARIO "SALÁRIO FIXO"
	FROM EMPREGADO;
    
-- UTILIZAÇÃO BÁSICA DO WHERE
SELECT NM_EMPREGADO, FUNCAO, SALARIO
	FROM EMPREGADO
    WHERE ID_EMPREGADO = 7788;

-- USANDO MAIS CONDICIONAIS
SELECT NM_EMPREGADO, FUNCAO, SALARIO
	FROM EMPREGADO
    WHERE ID_DEPARTAMENTO = 10 AND SALARIO >= 1300;

-- VERIFICANDO NOMES QUE COMEÇAM EM A (% OR _)
SELECT NM_EMPREGADO, FUNCAO, SALARIO
	FROM EMPREGADO
    WHERE NM_EMPREGADO LIKE 'A%';

-- COMPARAÇÃO
SELECT NM_EMPREGADO, FUNCAO, SALARIO
	FROM EMPREGADO
    WHERE COMISSAO IS NULL;

-- PASSANDO MAIS DE UM PARAMETRO
SELECT NM_EMPREGADO, FUNCAO, SALARIO
	FROM EMPREGADO
    WHERE ID_DEPARTAMENTO IN (10,30);
    
SELECT NM_EMPREGADO, FUNCAO, SALARIO
	FROM EMPREGADO
    WHERE ID_DEPARTAMENTO = 10 OR ID_DEPARTAMENTO = 30;
    
-- SELEÇÃO DE INTERVALOS DE VALORES
SELECT NM_EMPREGADO, FUNCAO, SALARIO
	FROM EMPREGADO
    WHERE SALARIO BETWEEN 800 AND 1200;

SELECT NM_EMPREGADO, FUNCAO, SALARIO
	FROM EMPREGADO
    WHERE SALARIO >= 800 AND SALARIO <= 1200;

-- COLOCAR EM ORDEM (ASC ORDEM REVERSA)
SELECT NM_EMPREGADO, FUNCAO, SALARIO
	FROM EMPREGADO
    ORDER BY NM_EMPREGADO;

-- MULTIPLAS COLUNAS
SELECT NM_EMPREGADO, FUNCAO, SALARIO
	FROM EMPREGADO
    ORDER BY FUNCAO DESC, NM_EMPREGADO DESC;
    
SELECT NM_EMPREGADO, FUNCAO, SALARIO
	FROM EMPREGADO
    WHERE UPPER(NM_EMPREGADO) LIKE BINARY'SMIT%';