/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.FornecedorDaoImpl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Fornecedor;

/**
 *
 * @author Professor
 */
public class FormFornecedor extends javax.swing.JInternalFrame {

    // Variavéis de Controle (FLAGS)
    public static boolean editFor = false;

    /**
     * Creates new form FormFornecedor
     */
    public FormFornecedor() {
        initComponents();
        loadForn();
        desativarCamposFor();
    }

    public boolean isAnyFilledFor() {
        boolean response = !jTfContatoFor.getText().isBlank()
                && !jTfEmailFor.getText().isBlank() && !jTfFoneFor.getText().isBlank()
                && !jTfNomeFor.getText().isBlank();
        return (response);
    }

    public void ativarCamposFor() {
        jTfCodFor.setEnabled(true);
        jTfContatoFor.setEnabled(true);
        jTfEmailFor.setEnabled(true);
        jTfFoneFor.setEnabled(true);
        jTfNomeFor.setEnabled(true);
    }

    public void desativarCamposFor() {
        jTfCodFor.setEnabled(false);
        jTfCodFor.setText("");
        jTfContatoFor.setEnabled(false);
        jTfContatoFor.setText("");
        jTfEmailFor.setEnabled(false);
        jTfEmailFor.setText("");
        jTfFoneFor.setEnabled(false);
        jTfFoneFor.setText("");
        jTfNomeFor.setEnabled(false);
        jTfNomeFor.setText("");

        jBtnSalvarFor.setEnabled(false);
        jBtnCancelarFor.setEnabled(false);
        jBtnExcluirFor.setEnabled(false);
        jBtnEditarFor.setEnabled(false);
    }

    FornecedorDaoImpl fornecedorImpl = new FornecedorDaoImpl();

    public void loadForn() {
        DefaultTableModel defaultFor = new DefaultTableModel(new Object[]{
            "Código",
            "Contato",
            "E-mail",
            "Telefone",
            "Empresa"
        }, 0);

        List<Fornecedor> fornecedores = fornecedorImpl.getAllFornecedores();
        for (Fornecedor fornecedor : fornecedores) {
            Object linha[] = new Object[]{
                fornecedor.getCod(),
                fornecedor.getContato(),
                fornecedor.getEmail(),
                fornecedor.getFone(),
                fornecedor.getEmpresa(),};
            defaultFor.addRow(linha);
        }
        jTblFor.setModel(defaultFor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTfNomeFor = new javax.swing.JTextField();
        jBtnExcluirFor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtnNovoFor = new javax.swing.JButton();
        jTfCodFor = new javax.swing.JTextField();
        jBtnEditarFor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnSalvarFor = new javax.swing.JButton();
        jTfContatoFor = new javax.swing.JTextField();
        jBtnCancelarFor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblFor = new javax.swing.JTable();
        jTfEmailFor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTfFoneFor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jTfNomeFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfNomeForKeyReleased(evt);
            }
        });

        jBtnExcluirFor.setText("Excluir");
        jBtnExcluirFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirForActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        jBtnNovoFor.setText("Novo");
        jBtnNovoFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoForActionPerformed(evt);
            }
        });

        jTfCodFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfCodForKeyReleased(evt);
            }
        });

        jBtnEditarFor.setText("Editar");
        jBtnEditarFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarForActionPerformed(evt);
            }
        });

        jLabel2.setText("Contato:");

        jBtnSalvarFor.setText("Salvar");
        jBtnSalvarFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarForActionPerformed(evt);
            }
        });

        jTfContatoFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfContatoForKeyReleased(evt);
            }
        });

        jBtnCancelarFor.setText("Cancelar");
        jBtnCancelarFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarForActionPerformed(evt);
            }
        });

        jLabel3.setText("Email:");

        jTblFor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Contato", "E-mail", "Telefone", "Empresa"
            }
        ));
        jTblFor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblForMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTblFor);

        jTfEmailFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfEmailForKeyReleased(evt);
            }
        });

        jLabel4.setText("Fone:");

        jTfFoneFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfFoneForKeyReleased(evt);
            }
        });

        jLabel5.setText("Empresa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jTfNomeFor, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(jTfFoneFor)
                    .addComponent(jTfEmailFor)
                    .addComponent(jTfContatoFor)
                    .addComponent(jTfCodFor))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jBtnNovoFor)
                .addGap(70, 70, 70)
                .addComponent(jBtnEditarFor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jBtnExcluirFor)
                .addGap(63, 63, 63)
                .addComponent(jBtnCancelarFor)
                .addGap(61, 61, 61)
                .addComponent(jBtnSalvarFor)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTfCodFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfContatoFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfEmailFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfFoneFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfNomeFor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnExcluirFor)
                    .addComponent(jBtnNovoFor)
                    .addComponent(jBtnEditarFor)
                    .addComponent(jBtnSalvarFor)
                    .addComponent(jBtnCancelarFor))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnNovoForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoForActionPerformed
        ativarCamposFor();
        jBtnCancelarFor.setEnabled(true);
        jBtnNovoFor.setEnabled(false);
        jBtnSalvarFor.setEnabled(false);
    }//GEN-LAST:event_jBtnNovoForActionPerformed

    private void jBtnEditarForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarForActionPerformed
        ativarCamposFor();
        editFor = true;
        jBtnSalvarFor.setEnabled(true);
        loadForn();
    }//GEN-LAST:event_jBtnEditarForActionPerformed

    private void jBtnExcluirForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirForActionPerformed
        int opt = JOptionPane.showConfirmDialog(null, 
                "Deseja realmente excluir este registro?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION) {
            fornecedorImpl.deleteFornecedor(Integer.parseInt(jTfCodFor.getText()));
            loadForn();
            desativarCamposFor();
            jBtnNovoFor.setEnabled(true);
        }
    }//GEN-LAST:event_jBtnExcluirForActionPerformed

    private void jBtnCancelarForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarForActionPerformed
        desativarCamposFor();

        jBtnCancelarFor.setEnabled(false);
        jBtnNovoFor.setEnabled(true);
        jBtnSalvarFor.setEnabled(false);
    }//GEN-LAST:event_jBtnCancelarForActionPerformed

    private void jBtnSalvarForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarForActionPerformed
        int cod = Integer.parseInt(jTfCodFor.getText());
        String empresa = jTfNomeFor.getText();
        String contato = jTfContatoFor.getText();
        String fone = jTfFoneFor.getText();
        String email = jTfEmailFor.getText();
        int a = JOptionPane.showConfirmDialog(null,
                "Deseja realmente salvar?\n\n"
                + "Código: " + cod
                + "\nEmpresa: " + empresa
                + "\nContato: " + contato
                + "\nEmail: " + email
                + "\nTelefone: " + fone,
                "Confirmar", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            Fornecedor fornecedor = new Fornecedor(cod, empresa, contato, fone, email);

            if (editFor) {
                fornecedorImpl.updateFornecedor(fornecedor);
                editFor = false;
            } else {
                fornecedorImpl.addFornecedor(fornecedor);
            }
            
            loadForn();

            desativarCamposFor();

            jBtnCancelarFor.setEnabled(false);
            jBtnNovoFor.setEnabled(true);
            jBtnSalvarFor.setEnabled(false);
        }
    }//GEN-LAST:event_jBtnSalvarForActionPerformed

    
    // Tecla pressionada
    private void jTfCodForKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfCodForKeyReleased
        jBtnSalvarFor.setEnabled(isAnyFilledFor());
    }//GEN-LAST:event_jTfCodForKeyReleased

    private void jTfContatoForKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfContatoForKeyReleased
        jBtnSalvarFor.setEnabled(isAnyFilledFor());
    }//GEN-LAST:event_jTfContatoForKeyReleased

    private void jTfEmailForKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfEmailForKeyReleased
        jBtnSalvarFor.setEnabled(isAnyFilledFor());
    }//GEN-LAST:event_jTfEmailForKeyReleased

    private void jTfFoneForKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfFoneForKeyReleased
        jBtnSalvarFor.setEnabled(isAnyFilledFor());
    }//GEN-LAST:event_jTfFoneForKeyReleased

    private void jTfNomeForKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfNomeForKeyReleased
        jBtnSalvarFor.setEnabled(isAnyFilledFor());
    }//GEN-LAST:event_jTfNomeForKeyReleased

    
    // Mouse
    private void jTblForMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblForMouseClicked
        int selectedRow = jTblFor.getSelectedRow();
        jBtnExcluirFor.setEnabled(true);
        jBtnEditarFor.setEnabled(true);
        if (jTblFor.getSelectedRow() != -1) {

            jTfCodFor.setText(jTblFor.getValueAt(selectedRow, 0).toString());
            jTfContatoFor.setText(jTblFor.getValueAt(selectedRow, 1).toString());
            jTfEmailFor.setText(jTblFor.getValueAt(selectedRow, 2).toString());
            jTfFoneFor.setText(jTblFor.getValueAt(selectedRow, 3).toString());
            jTfNomeFor.setText(jTblFor.getValueAt(selectedRow, 4).toString());
        }
    }//GEN-LAST:event_jTblForMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelarFor;
    private javax.swing.JButton jBtnEditarFor;
    private javax.swing.JButton jBtnExcluirFor;
    private javax.swing.JButton jBtnNovoFor;
    private javax.swing.JButton jBtnSalvarFor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblFor;
    private javax.swing.JTextField jTfCodFor;
    private javax.swing.JTextField jTfContatoFor;
    private javax.swing.JTextField jTfEmailFor;
    private javax.swing.JTextField jTfFoneFor;
    private javax.swing.JTextField jTfNomeFor;
    // End of variables declaration//GEN-END:variables
}
