/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.ClienteDaoImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 *
 * @author Professor
 */
public class FormCliente extends javax.swing.JInternalFrame {

    // Variavéis de Controle (FLAGS)
    public static boolean editCli = false;

    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
        loadCli();
        desativarCamposCli();
    }

    public boolean isAnyFilledCli() {
        boolean response = !jTfNomeCli.getText().isBlank()
                && !jTfEmailCli.getText().isBlank() && !jTfFoneCli.getText().isBlank()
                && !jTfEnderecoCli.getText().isBlank();
        return (response);
    }

    public void ativarCamposCli() {
        jTfCodCli.setEnabled(true);
        jTfNomeCli.setEnabled(true);
        jTfFoneCli.setEnabled(true);
        jTfEmailCli.setEnabled(true);
        jTfEnderecoCli.setEnabled(true);
    }

    public void desativarCamposCli() {
        jTfCodCli.setEnabled(false);
        jTfCodCli.setText("");
        jTfNomeCli.setEnabled(false);
        jTfNomeCli.setText("");
        jTfFoneCli.setEnabled(false);
        jTfFoneCli.setText("");
        jTfEmailCli.setEnabled(false);
        jTfEmailCli.setText("");
        jTfEnderecoCli.setEnabled(false);
        jTfEnderecoCli.setText("");

        jBtnSalvarCli.setEnabled(false);
        jBtnCancelarCli.setEnabled(false);
        jBtnExcluirCli.setEnabled(false);
        jBtnEditarCli.setEnabled(false);
    }

    ClienteDaoImpl clienteImpl = new ClienteDaoImpl();

    public void loadCli() {
        DefaultTableModel defaultCli = new DefaultTableModel(new Object[]{
            "Código",
            "Nome",
            "Fone",
            "Email",
            "Endereco"
        }, 0);
        List<Cliente> clientes = clienteImpl.getAllClientes();
        for (Cliente cliente : clientes) {
            Object linha[] = new Object[]{
                cliente.getCodigo(),
                cliente.getNome(),
                cliente.getFone(),
                cliente.getEmail(),
                cliente.getEndereco(),};
            defaultCli.addRow(linha);
        }
        jTblCli.setModel(defaultCli);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnExcluirCli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtnNovoCli = new javax.swing.JButton();
        jTfCodCli = new javax.swing.JTextField();
        jBtnEditarCli = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnSalvarCli = new javax.swing.JButton();
        jTfNomeCli = new javax.swing.JTextField();
        jBtnCancelarCli = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblCli = new javax.swing.JTable();
        jTfFoneCli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTfEmailCli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTfEnderecoCli = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jBtnExcluirCli.setText("Excluir");
        jBtnExcluirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirCliActionPerformed(evt);
            }
        });

        jLabel1.setText("Matrícula:");

        jBtnNovoCli.setText("Novo");
        jBtnNovoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoCliActionPerformed(evt);
            }
        });

        jTfCodCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfCodCliKeyReleased(evt);
            }
        });

        jBtnEditarCli.setText("Editar");
        jBtnEditarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarCliActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jBtnSalvarCli.setText("Salvar");
        jBtnSalvarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarCliActionPerformed(evt);
            }
        });

        jTfNomeCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfNomeCliKeyReleased(evt);
            }
        });

        jBtnCancelarCli.setText("Cancelar");
        jBtnCancelarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarCliActionPerformed(evt);
            }
        });

        jLabel3.setText("Fone:");

        jTblCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Nome", "Fone", "Email", "Endereço"
            }
        ));
        jTblCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblCliMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTblCli);

        jTfFoneCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfFoneCliKeyReleased(evt);
            }
        });

        jLabel4.setText("Email:");

        jTfEmailCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfEmailCliKeyReleased(evt);
            }
        });

        jLabel5.setText("Endereço:");

        jTfEnderecoCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfEnderecoCliKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jTfEnderecoCli, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(jTfEmailCli)
                    .addComponent(jTfFoneCli)
                    .addComponent(jTfNomeCli)
                    .addComponent(jTfCodCli))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jBtnNovoCli)
                .addGap(70, 70, 70)
                .addComponent(jBtnEditarCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jBtnExcluirCli)
                .addGap(63, 63, 63)
                .addComponent(jBtnCancelarCli)
                .addGap(61, 61, 61)
                .addComponent(jBtnSalvarCli)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTfCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTfFoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfEnderecoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnExcluirCli)
                    .addComponent(jBtnNovoCli)
                    .addComponent(jBtnEditarCli)
                    .addComponent(jBtnSalvarCli)
                    .addComponent(jBtnCancelarCli))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Ações dos Botões
    private void jBtnNovoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoCliActionPerformed
        ativarCamposCli();

        jBtnCancelarCli.setEnabled(true);
        jBtnNovoCli.setEnabled(false);
        jBtnSalvarCli.setEnabled(false);
    }//GEN-LAST:event_jBtnNovoCliActionPerformed

    private void jBtnSalvarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarCliActionPerformed
        int cod = Integer.parseInt(jTfCodCli.getText());
        String nome = jTfNomeCli.getText();
        String telefone = jTfFoneCli.getText();
        String email = jTfEmailCli.getText();
        String endereco = jTfEnderecoCli.getText();
        int a = JOptionPane.showConfirmDialog(null,
                "Deseja realmente salvar?\n\n"
                + "Código: " + cod
                + "\nNome: " + nome
                + "\nTelefone: " + telefone
                + "\nEmail: " + email
                + "\nEnderço: " + endereco,
                "Confirmar", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            Cliente cliente = new Cliente(cod, nome, telefone, email, endereco);

            if (editCli) {
                clienteImpl.updateCliente(cliente);
                editCli = false;
            } else {
                clienteImpl.addCliente(cliente);
            }

            loadCli();

            desativarCamposCli();

            jBtnCancelarCli.setEnabled(false);
            jBtnNovoCli.setEnabled(true);
            jBtnSalvarCli.setEnabled(false);
        }
    }//GEN-LAST:event_jBtnSalvarCliActionPerformed

    private void jBtnCancelarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarCliActionPerformed
        desativarCamposCli();

        jBtnCancelarCli.setEnabled(false);
        jBtnNovoCli.setEnabled(true);
        jBtnSalvarCli.setEnabled(false);
    }//GEN-LAST:event_jBtnCancelarCliActionPerformed

    private void jBtnExcluirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirCliActionPerformed
        int opt = JOptionPane.showConfirmDialog(null, 
                "Deseja realmente excluir este registro?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION) {
            clienteImpl.deleteCliente(Integer.parseInt(jTfCodCli.getText()));
            loadCli();
            desativarCamposCli();
            jBtnNovoCli.setEnabled(true);
        }
    }//GEN-LAST:event_jBtnExcluirCliActionPerformed

    private void jBtnEditarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarCliActionPerformed
        ativarCamposCli();
        editCli = true;
        jBtnSalvarCli.setEnabled(true);
        loadCli();
    }//GEN-LAST:event_jBtnEditarCliActionPerformed

    // Tecla pressionada
    private void jTfCodCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfCodCliKeyReleased
        jBtnSalvarCli.setEnabled(isAnyFilledCli());
    }//GEN-LAST:event_jTfCodCliKeyReleased

    private void jTfNomeCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfNomeCliKeyReleased
        jBtnSalvarCli.setEnabled(isAnyFilledCli());
    }//GEN-LAST:event_jTfNomeCliKeyReleased

    private void jTfFoneCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfFoneCliKeyReleased
        jBtnSalvarCli.setEnabled(isAnyFilledCli());
    }//GEN-LAST:event_jTfFoneCliKeyReleased

    private void jTfEmailCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfEmailCliKeyReleased
        jBtnSalvarCli.setEnabled(isAnyFilledCli());
    }//GEN-LAST:event_jTfEmailCliKeyReleased

    private void jTfEnderecoCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfEnderecoCliKeyReleased
        jBtnSalvarCli.setEnabled(isAnyFilledCli());
    }//GEN-LAST:event_jTfEnderecoCliKeyReleased

    //Clique do Mouse
    private void jTblCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblCliMouseClicked
        int selectedRow = jTblCli.getSelectedRow();
        jBtnExcluirCli.setEnabled(true);
        jBtnEditarCli.setEnabled(true);
        if (jTblCli.getSelectedRow() != -1) {

            jTfCodCli.setText(jTblCli.getValueAt(selectedRow, 0).toString());
            jTfNomeCli.setText(jTblCli.getValueAt(selectedRow, 1).toString());
            jTfFoneCli.setText(jTblCli.getValueAt(selectedRow, 2).toString());
            jTfEmailCli.setText(jTblCli.getValueAt(selectedRow, 3).toString());
            jTfEnderecoCli.setText(jTblCli.getValueAt(selectedRow, 4).toString());
        }
    }//GEN-LAST:event_jTblCliMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelarCli;
    private javax.swing.JButton jBtnEditarCli;
    private javax.swing.JButton jBtnExcluirCli;
    private javax.swing.JButton jBtnNovoCli;
    private javax.swing.JButton jBtnSalvarCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblCli;
    private javax.swing.JTextField jTfCodCli;
    private javax.swing.JTextField jTfEmailCli;
    private javax.swing.JTextField jTfEnderecoCli;
    private javax.swing.JTextField jTfFoneCli;
    private javax.swing.JTextField jTfNomeCli;
    // End of variables declaration//GEN-END:variables
}
