/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CarroDao;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Carro;

/**
 *
 * @author gabriel_piske
 */
public class CadCar_view extends javax.swing.JFrame {

    private Carro carro;

    /**
     * Creates new form CadCar_view
     */
    
    // Construtor base da tela 
    public CadCar_view() {
        initComponents();

        // Define os títulos das colunas da tabela.
        String[] titles = {"Código", "Descrição", "Potência", "Cor"};
        for (int i = 0; i < titles.length; i++) {
            jtblCarros.getColumnModel().getColumn(i).setHeaderValue(titles[i]);
        }

        jtxtCod.setEnabled(false);
        gerarID();
        loadData();
        
        // Listener para quando uma linha da tabela é selecionada
        jtblCarros.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                if (!evt.getValueIsAdjusting()) {
                    int row = jtblCarros.getSelectedRow();
                    if (row != -1) {
                        // Preencher os campos com os dados da linha selecionada
                        jtxtCod.setText(jtblCarros.getValueAt(row, 0).toString());
                        jtxtDesc.setText(jtblCarros.getValueAt(row, 1).toString());
                        jtxtPot.setText(jtblCarros.getValueAt(row, 2).toString());
                        jtxtCor.setText(jtblCarros.getValueAt(row, 3).toString());
                    }
                }
            }
        });

    }

    // Gera automaticamente o próximo ID para o carro a ser cadastrado.
    public void gerarID() {
        CarroDao dao = new CarroDao();
        ArrayList<Carro> listaCarros = dao.getCarros();

        if (listaCarros.isEmpty()) {
            jtxtCod.setText("1");
        } else {
            int lastID = listaCarros.get(listaCarros.size() - 1).getCod_carro();
            jtxtCod.setText(String.valueOf(lastID + 1));
        }
    }

    //  Pergunta ao usuário se deseja carregar os dados antigos
    public void loadData() {
        int result = JOptionPane.showConfirmDialog(null,
                "Deseja carregar os dados Antigos?", null, JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            listarDados();
        }
    }

    // Carrega todos os dados dos carros cadastrados e exibe na tabela
    public void listarDados() {
        DefaultTableModel model = (DefaultTableModel) jtblCarros.getModel();
        model.setRowCount(0);

        CarroDao carDao = new CarroDao();
        ArrayList<Carro> listCar = new ArrayList<>();
        listCar = carDao.getCarros();
        for (Carro carro : listCar) {
            Object[] linha = {
                carro.getCod_carro(),
                carro.getDesc_carro(),
                carro.getPot_carro(),
                carro.getCor_carro()
            };
            model.addRow(linha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtnCad = new javax.swing.JButton();
        jbtnDel = new javax.swing.JButton();
        jbtnList = new javax.swing.JButton();
        jbtnAlt = new javax.swing.JButton();
        jtxtCod = new javax.swing.JTextField();
        jtxtDesc = new javax.swing.JTextField();
        jtxtPot = new javax.swing.JTextField();
        jtxtCor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblCarros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Carros");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro de Carros");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Código");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Descrição");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Potência");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cor");

        jbtnCad.setText("Cadastrar");
        jbtnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCadActionPerformed(evt);
            }
        });

        jbtnDel.setText("Deletar");
        jbtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDelActionPerformed(evt);
            }
        });

        jbtnList.setText("Listar");
        jbtnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListActionPerformed(evt);
            }
        });

        jbtnAlt.setText("Alterar");
        jbtnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAltActionPerformed(evt);
            }
        });

        jtxtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodActionPerformed(evt);
            }
        });

        jtblCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblCarros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jbtnCad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtnDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnList, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtxtCod)
                            .addComponent(jtxtDesc)
                            .addComponent(jtxtPot)
                            .addComponent(jtxtCor))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtPot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCad)
                    .addComponent(jbtnDel)
                    .addComponent(jbtnList)
                    .addComponent(jbtnAlt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Cadastra um novo carro se todos os campos estiverem preenchidos.
    private void jbtnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCadActionPerformed
        if (!jtxtCod.getText().isBlank() && !jtxtCor.getText().isBlank()
                && !jtxtDesc.getText().isBlank() && !jtxtPot.getText().isBlank()) {
            CarroDao dao = new CarroDao();
            carro = new Carro(Integer.parseInt(jtxtCod.getText()), jtxtDesc.getText(), Integer.parseInt(jtxtPot.getText()), jtxtCor.getText());
            dao.cadCar(carro);

            // Limpa os campos de texto após cadastro.
            jtxtCod.setText("");
            jtxtCor.setText("");
            jtxtDesc.setText("");
            jtxtPot.setText("");
            gerarID();
            listarDados();
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente.");
        }
    }//GEN-LAST:event_jbtnCadActionPerformed

    private void jtxtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodActionPerformed
    
    // Carrega os dados da tabela quando o botão "Listar" é clicado
    private void jbtnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListActionPerformed
        listarDados();
    }//GEN-LAST:event_jbtnListActionPerformed

    // Deleta o carro selecionado na tabela, se houver uma linha selecionada
    private void jbtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDelActionPerformed
        CarroDao dao = new CarroDao();
        int lineSelect = jtblCarros.getSelectedRow();
        if (lineSelect != 1) {
            int codCarro = (int) jtblCarros.getValueAt(lineSelect, 0);
            try {
                dao.deleteCar(codCarro);
                JOptionPane.showMessageDialog(null, "Carro Excluido");
                listarDados();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Selecione uma linha para excluit");
            }
        }
    }//GEN-LAST:event_jbtnDelActionPerformed

    // Atualiza os dados de um carro existente, se todos os campos estiverem preenchidos
    private void jbtnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAltActionPerformed
        if (!jtxtCod.getText().isBlank() && !jtxtCor.getText().isBlank()
                && !jtxtDesc.getText().isBlank() && !jtxtPot.getText().isBlank()) {
            CarroDao dao = new CarroDao();
            carro = new Carro(Integer.parseInt(jtxtCod.getText()), jtxtDesc.getText(), Integer.parseInt(jtxtPot.getText()), jtxtCor.getText());
            dao.alterarCarro(carro);

            JOptionPane.showMessageDialog(null, "Carro alterado");
            listarDados();

            jtblCarros.clearSelection();
            jtxtCod.setText("");
            jtxtDesc.setText("");
            jtxtPot.setText(""); 
            jtxtCor.setText(""); 
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os dados de forma correta");
        }
    }//GEN-LAST:event_jbtnAltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCar_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCar_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCar_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCar_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCar_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAlt;
    private javax.swing.JButton jbtnCad;
    private javax.swing.JButton jbtnDel;
    private javax.swing.JButton jbtnList;
    private javax.swing.JTable jtblCarros;
    private javax.swing.JTextField jtxtCod;
    private javax.swing.JTextField jtxtCor;
    private javax.swing.JTextField jtxtDesc;
    private javax.swing.JTextField jtxtPot;
    // End of variables declaration//GEN-END:variables
}
