create database bdnotafiscal;
use bdnotafiscal;

-- TABELA CLIENTE
CREATE TABLE CLIENTE (
    idCliente INT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    endereco VARCHAR(100) NOT NULL
);

-- TABELA VENDEDOR
CREATE TABLE VENDEDOR (
    idVendedor INT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL
);

-- TABELA PRODUTO
CREATE TABLE PRODUTO (
    idProduto INT PRIMARY KEY,
    descricao VARCHAR(45) NOT NULL,
    unidade VARCHAR(2) NOT NULL,
    preco DECIMAL NOT NULL
);

-- TABELA NOTA FISCAL
CREATE TABLE NOTAFISCAL (
    idNotaFiscal INT PRIMARY KEY,
    dataEmissao DATE NOT NULL,
    totalNota DECIMAL NOT NULL,
    idCliente INT NOT NULL,
    idVendedor INT NOT NULL,
    CONSTRAINT NOTAFISCAL_IDCLIENTE_FK FOREIGN KEY (idCliente) REFERENCES CLIENTE (idCliente),
    CONSTRAINT NOTAFISCAL_IDVENDEDOR_FK FOREIGN KEY (idVendedor) REFERENCES VENDEDOR (idVendedor)
);

-- TABELA ITEM NOTA FISCAL
CREATE TABLE ITEMNOTAFISCAL (
    idNotaFiscal INT NOT NULL,
    idProduto INT NOT NULL,
    quantidade INT NOT NULL,
    totalProduto DECIMAL NOT NULL,
    CONSTRAINT ITEMNOTAFISCAL_IDNOTAFISCAL_FK FOREIGN KEY (idNotaFiscal) REFERENCES NOTAFISCAL(idNotaFiscal),
    CONSTRAINT ITEMNOTAFISCAL_IDPRODUTO_FK FOREIGN KEY (idProduto) REFERENCES PRODUTO(idProduto)
)