/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author Professor
 */
public class FormCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnExcluirCli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtnNovoCli = new javax.swing.JButton();
        jTfCodCli = new javax.swing.JTextField();
        jBtnEditarCli = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnSalvarCli = new javax.swing.JButton();
        jTfNomeCli = new javax.swing.JTextField();
        jBtnCancelarCli = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblCli = new javax.swing.JTable();
        jTfFoneCli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTfEmailCli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTfEnderecoCli = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jBtnExcluirCli.setText("Excluir");

        jLabel1.setText("Matrícula:");

        jBtnNovoCli.setText("Novo");
        jBtnNovoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoCliActionPerformed(evt);
            }
        });

        jBtnEditarCli.setText("Editar");

        jLabel2.setText("Nome:");

        jBtnSalvarCli.setText("Salvar");
        jBtnSalvarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarCliActionPerformed(evt);
            }
        });

        jBtnCancelarCli.setText("Cancelar");

        jLabel3.setText("Fone:");

        jTblCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Nome", "Fone", "Email", "Endereço"
            }
        ));
        jScrollPane2.setViewportView(jTblCli);

        jLabel4.setText("Email:");

        jLabel5.setText("Endereço:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jTfEnderecoCli, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(jTfEmailCli)
                    .addComponent(jTfFoneCli)
                    .addComponent(jTfNomeCli)
                    .addComponent(jTfCodCli))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jBtnNovoCli)
                .addGap(70, 70, 70)
                .addComponent(jBtnEditarCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jBtnExcluirCli)
                .addGap(63, 63, 63)
                .addComponent(jBtnCancelarCli)
                .addGap(61, 61, 61)
                .addComponent(jBtnSalvarCli)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTfCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTfFoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfEnderecoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnExcluirCli)
                    .addComponent(jBtnNovoCli)
                    .addComponent(jBtnEditarCli)
                    .addComponent(jBtnSalvarCli)
                    .addComponent(jBtnCancelarCli))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnNovoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnNovoCliActionPerformed

    private void jBtnSalvarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarCliActionPerformed

    }//GEN-LAST:event_jBtnSalvarCliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelarCli;
    private javax.swing.JButton jBtnEditarCli;
    private javax.swing.JButton jBtnExcluirCli;
    private javax.swing.JButton jBtnNovoCli;
    private javax.swing.JButton jBtnSalvarCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblCli;
    private javax.swing.JTextField jTfCodCli;
    private javax.swing.JTextField jTfEmailCli;
    private javax.swing.JTextField jTfEnderecoCli;
    private javax.swing.JTextField jTfFoneCli;
    private javax.swing.JTextField jTfNomeCli;
    // End of variables declaration//GEN-END:variables
}
