/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gabriel_piske
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jblTitle = new javax.swing.JLabel();
        jtxtPesquisa = new javax.swing.JTextField();
        jblPesquisa = new javax.swing.JLabel();
        jblRealizarVenda = new javax.swing.JLabel();
        jblNovoProduto = new javax.swing.JLabel();
        jblNovoFuncionario = new javax.swing.JLabel();
        jblNovoFornecedor = new javax.swing.JLabel();
        jbtnNovoProduto = new javax.swing.JButton();
        jbtnNovoFornecedor = new javax.swing.JButton();
        jbtnNovoFuncionario = new javax.swing.JButton();
        jscrlAreaDeBusca = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jbtnVender = new javax.swing.JButton();

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jblTitle.setText("ABC - Autopeças");

        jtxtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPesquisaActionPerformed(evt);
            }
        });

        jblPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jblPesquisa.setText("Realizar Pesquisa: ");

        jblRealizarVenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jblRealizarVenda.setText("Realizar Venda");

        jblNovoProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jblNovoProduto.setText("Cadastrar Novo Produto");

        jblNovoFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jblNovoFuncionario.setText("Cadastrar Novo Funcionario");

        jblNovoFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jblNovoFornecedor.setText("Cadastrar Novo Fornecedor");

        jbtnNovoProduto.setText("Novo Produto");
        jbtnNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNovoProdutoActionPerformed(evt);
            }
        });

        jbtnNovoFornecedor.setText("Novo Fornecedor");
        jbtnNovoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNovoFornecedorActionPerformed(evt);
            }
        });

        jbtnNovoFuncionario.setText("Novo Funcionário");
        jbtnNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNovoFuncionarioActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jscrlAreaDeBusca.setViewportView(jTextArea1);

        jbtnVender.setText("Vender");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jscrlAreaDeBusca)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jblPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtPesquisa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblNovoFuncionario)
                            .addComponent(jblNovoProduto)
                            .addComponent(jblNovoFornecedor, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnNovoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnNovoFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnNovoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jblRealizarVenda)
                        .addGap(94, 94, 94)
                        .addComponent(jbtnVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscrlAreaDeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblRealizarVenda)
                    .addComponent(jbtnVender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnNovoProduto)
                    .addComponent(jblNovoProduto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnNovoFornecedor)
                    .addComponent(jblNovoFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblNovoFuncionario)
                    .addComponent(jbtnNovoFuncionario))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPesquisaActionPerformed

    private void jbtnNovoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNovoFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnNovoFornecedorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbtnNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNovoProdutoActionPerformed
        // TODO add your handling code here:
        cadPecas telaPecas = new cadPecas();
        telaPecas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnNovoProdutoActionPerformed

    private void jbtnNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNovoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnNovoFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jblNovoFornecedor;
    private javax.swing.JLabel jblNovoFuncionario;
    private javax.swing.JLabel jblNovoProduto;
    private javax.swing.JLabel jblPesquisa;
    private javax.swing.JLabel jblRealizarVenda;
    private javax.swing.JLabel jblTitle;
    private javax.swing.JButton jbtnNovoFornecedor;
    private javax.swing.JButton jbtnNovoFuncionario;
    private javax.swing.JButton jbtnNovoProduto;
    private javax.swing.JButton jbtnVender;
    private javax.swing.JScrollPane jscrlAreaDeBusca;
    private javax.swing.JTextField jtxtPesquisa;
    // End of variables declaration//GEN-END:variables
}
